### ISSUE TITLE
更新 feeds 时出错

### ISSUE THREAD

**Issue by Oniokey** [KyleRicardo/MentoHUST-OpenWrt-ipk#17]
在执行`./scripts/feeds update -a`之后出现
> ……
Checking` 'python3-distutils'... failed.
……
Build dependency: Please install the Python3 distutils module
Prerequisite check failed. Use FORCE=1 to override.
make: *** [/home/oniokey/下载/openwrt-sdk-ramips-mt7621/include/toplevel.mk:181：/home/oniokey/下载/openwrt-sdk-ramips-mt7621/staging_dir/host/.prereq-build] 错误 1
/home/oniokey/下载/openwrt-sdk-ramips-mt7621/staging_dir/host/bin/sed: 行 5: /home/oniokey/下载/openwrt-sdk-ramips-mt7621/staging_dir/host/bin/../lib/ld-linux-x86-64.so.2：无法执行二进制文件: 可执行文件格式错误
……

后续的步骤中也出现了
> Build dependency: Please install the Python3 distutils module
等类似的错误

系统是 Ubuntu 20.04.5 LTS 运行在 MacBook Pro M1 Parallels Desktop 18 上

**Comment by KyleRicardo** [comment]
Try `sudo apt-get install python3-distutils`.

**Comment by TodayNow** [comment]
感谢作者秒回，尝试后，依旧出现错误

> Create index file './feeds/base.index' 
/home/oniokey/下载/openwrt/staging_dir/host/bin/xargs: 行 5: /home/oniokey/下载/openwrt/staging_dir/host/bin/../lib/ld-linux-x86-64.so.2：无法执行二进制文件: 可执行文件格式错误
/home/oniokey/下载/openwrt/staging_dir/host/bin/xargs: 行 5: /home/oniokey/下载/openwrt/staging_dir/host/bin/../lib/ld-linux-x86-64.so.2: 成功
/home/oniokey/下载/openwrt/staging_dir/host/bin/sed: 行 5: /home/oniokey/下载/openwrt/staging_dir/host/bin/../lib/ld-linux-x86-64.so.2：无法执行二进制文件: 可执行文件格式错误
……

且忽略该错误继续执行`./scripts/feeds install libpcap`时出现如下错误

> /home/oniokey/下载/openwrt/staging_dir/host/bin/sed: line 5: /home/oniokey/下载/openwrt/staging_dir/host/bin/../lib/ld-linux-x86-64.so.2: cannot execute binary file: Exec format error
/home/oniokey/下载/openwrt/staging_dir/host/bin/sed: line 5: /home/oniokey/下载/openwrt/staging_dir/host/bin/../lib/ld-linux-x86-64.so.2: Success
/home/oniokey/下载/openwrt/staging_dir/host/bin/sed: line 5: /home/oniokey/下载/openwrt/staging_dir/host/bin/../lib/ld-linux-x86-64.so.2: cannot execute binary file: Exec format error
……

**Comment by KyleRicardo** [comment]
提供一下你的路由器具体型号，我在我的虚拟机中帮你看一眼编译过程。似乎你的SDK里的executable bin的arch不对。

**Comment by TodayNow** [comment]
小米 AC2100

**Comment by KyleRicardo** [comment]
这个型号比较常见，如果你不想花时间在编译上面，正好可以看看 #16 Release的版本。

**Comment by TodayNow** [comment]
好的，感谢
