### ISSUE TITLE
安装后无法运行

### ISSUE THREAD

**Issue by Chengyuan-artist** [KyleRicardo/MentoHUST-OpenWrt-ipk#18]
路由器型号：Phicomm K2P
路由器SoC：MediaTek MT7621
<img width="193" alt="image" src="https://github.com/KyleRicardo/MentoHUST-OpenWrt-ipk/assets/56594167/13ccc803-562a-4d60-9f03-76dbc91f1680">

安装过程顺利：
<img width="603" alt="image" src="https://github.com/KyleRicardo/MentoHUST-OpenWrt-ipk/assets/56594167/33d44164-9455-4c14-b3b1-4f8871c6bac4">

运行出现如下报错：
<img width="378" alt="image" src="https://github.com/KyleRicardo/MentoHUST-OpenWrt-ipk/assets/56594167/d82e7dec-1ae7-4716-8213-58f0313c6a6f">

**Comment by KyleRicardo** [comment]
Fallback到OpenWrt21.02版本重新编译了Release，请重新下载试下。

**Comment by Chengyuan-artist** [comment]
感谢！可以使用了>ω<
