### ISSUE TITLE
关于使用时的问题

### ISSUE THREAD

**Issue by LFFAnd** [KyleRicardo/MentoHUST-OpenWrt-ipk#19]
root@OpenWrt:~# ** 用户名:      202240700126
** 网卡:        eth0.2
** 认证超时:    8秒
** 响应间隔:    30秒
** 失败等待:    15秒
** 允许失败:    0次
** 组播地址:    锐捷
** DHCP方式:    二次认证
** DHCP脚本:    udhcpc -i eth0.2
!! 在网卡eth0.2上获取IP失败!
!! 在网卡eth0.2上获取子网掩码失败!
** 本机MAC:     98:8f:e0:66:28:cd
** 使用IP:      0.0.0.0
** 子网掩码:    255.255.255.0
>> 寻找服务器...
>> 找不到服务器，重启认证!
>> 寻找服务器...
一直显示这个 但用老毛子自带的mentohust就能登陆上 请问能提供一些思路吗

**Comment by KyleRicardo** [comment]
不知你那边网络环境，无法提供具体解决方案。建议把老毛子的配置文件mentohust.conf跟这个对比下，或者直接拿过来用用，看看是否有效。

**Comment by LFFAnd** [comment]
好的 我去比较比较

**Comment by LFFAnd** [comment]
你好 他还是显示无法解决 我把那个老毛子的mentohust的文件发给大佬你 大佬是否能进行分析分析

**Comment by KyleRicardo** [comment]
你看一下是不是网卡选错了，确定WAN口的网卡是eth0.2吗？可以ifconfig看一下IP。

**Comment by LFFAnd** [comment]
感谢大佬的及时解答 已经找到问题了 原来是编译固件的时候自动把路由器物理千兆的lan口改为wan口了 大佬知道咋改wan lan口

**Comment by KyleRicardo** [comment]
感觉只能重新编译下固件了，没这样用过。你是什么路由器，只有一个lan口吗？那你把网线接lan口然后找到对应的网卡eth再试试也行。

**Comment by LFFAnd** [comment]
就是用原来的lan口就解决了 感谢老哥的及时解答

**Comment by KyleRicardo** [comment]
解决了就好，不必客气。
Closing.
