### ISSUE TITLE
认证时反应“不允许使用的客户端类型!”

### ISSUE THREAD

**Issue by SeasyecN** [KyleRicardo/MentoHUST-OpenWrt-ipk#23]
型号是新华3
### 日志
** 用户名:	202105***
** 网卡: 	macvlan2
** 智能重连:	255.255.****
** 认证超时:	8秒
** 响应间隔:	30秒
** 失败等待:	15秒
** 允许失败:	0次
** 组播地址:	标准
** DHCP方式:	认证后
** DHCP脚本:	dhclient
** 本机MAC:	e2:ce:80:b2:cb:63
** 使用IP:	172.18****
** 子网掩码:	255.255.192.0
** 认证参数已成功保存到/etc/mentohust.conf.
>> 寻找服务器...
** 认证MAC:	00:1a:a9:17****
>> 发送用户名...
>> 发送密码...
>> 认证失败!
$$ 系统提示:	不允许使用的客户端类型!
### 原因
学校更换交换机升级

**Comment by KyleRicardo** [comment]
这个可能是版本升级导致，可能需要抓包分析正版客户端报文的变化。

**Comment by SeasyecN** [comment]
> 这个可能是版本升级导致，可能需要抓包分析正版客户端报文的变化。

是升级版本导致的，查阅了古早的mentohust的资料设置版本参数>5.0解决
