### ISSUE TITLE
dl.7z 文件，阿里云盘链接

### ISSUE THREAD

**Issue by Leojc** [KyleRicardo/MentoHUST-OpenWrt-ipk#6]
百度云还是挺慢的，搞了一个阿里云盘。不过阿里云盘不支持压缩包分享，所以我把它伪装成图片了哈哈。

我用阿里云盘分享了「dl.7z」，你可以不限速下载🚀
复制这段内容打开「阿里云盘」App 即可获取
链接：https://www.aliyundrive.com/s/zynUAKkyMD5

**Comment by KyleRicardo** [comment]
感谢提供，不过现在科学上网变简单了，大概率用不到这种东西了，哈哈哈
13年那会儿架梯子还在搞什么GoAgent来着

**Comment by Leojc** [comment]
> 感谢提供，不过现在科学上网变简单了，大概率用不到这种东西了，哈哈哈 13年那会儿架梯子还在搞什么GoAgent来着

哈哈，然而百度云雷打不动10KB/s，任你科学上网还是万兆带宽，[滑稽.jpg]
