### ISSUE TITLE
改一个地方，可以加快若干倍

### ISSUE THREAD

**Issue by Leojc** [KyleRicardo/MentoHUST-OpenWrt-ipk#7]
把make全换成make -j$((\`nproc\`+1))
作用是开启多线程编译

**Comment by KyleRicardo** [comment]
加入此参数后有概率出现编译错误，所以没有在文档内提及。
如果用户加入此参数可以顺利编译，那么这是一件好事。

**Comment by Leojc** [comment]
嗯嗯，不过我倒是觉得可以把这个作为默认，然后下面加一句如果报错，再换成make。毕竟单线程确实超级慢了。
