### ISSUE TITLE
安装编译libpcap库步骤出现问题

### ISSUE THREAD

**Issue by Shennoter** [KyleRicardo/MentoHUST-OpenWrt-ipk#8]
有严格按照readme执行，使用的是wsl2 kali，在执行`$ ./scripts/feeds install libpcap`这条命令后出现了如下报错，请问这些缺失的文件应该在哪里下载呢，忽略这个错误继续向下执行完毕后编译出来的libpcap文件是空的。

Collecting package info: done
Collecting target info: done
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'eip197-mini-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'r8169-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'e100-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'bnx2-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'bnx2x-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'ar3k-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'mwifiex-sdio-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb2', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'edgeport-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb3', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'amdgpu-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'radeon-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'prism54-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'rtl8192su-firmware', which does not exist
Installing package 'libpcap' from base

**Comment by KyleRicardo** [comment]
这个不是编译的命令，只是让feeds知道我们需要libpcap。这段也不是报错，只是警告，在后面编译mentohust的时候你是可以成功编译的。

**Comment by Shennoter** [comment]
谢谢大佬的秒回，其实我是编译完成在openwrt安装之后在终端试运行mentohust时有如下的报错，然后从头开始排查原因才会以为是这里的问题，请问这是什么原因呢
root@OpenWrt:/usr/sbin# mentohust 
Error relocating /usr/lib/libpcap.so.1: __stat_time64: symbol not found
Error relocating /usr/lib/libpcap.so.1: __select_time64: symbol not found
Error relocating /usr/sbin/mentohust: __dlsym_time64: symbol not found
Error relocating /usr/sbin/mentohust: __setitimer_time64: symbol not found

**Comment by KyleRicardo** [comment]
SDK比较新，而你的openwrt系统比较老所致。新版libc用了64位的时间相关api。
`cat /etc/openwrt_release`我看下你的输出是啥先。

**Comment by Shennoter** [comment]
`root@OpenWrt:~# cat /etc/openwrt_release`
DISTRIB_ID='ImmortalWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r18870-4dfd4f2e4c'
DISTRIB_TARGET='ramips/mt7621'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='ImmortalWrt SNAPSHOT r18870-4dfd4f2e4c'
DISTRIB_TAINTS='no-all'

**Comment by KyleRicardo** [comment]
Redmi AC2100路由器？

> The musl version upgrade in September changed the internal time handling from 32bit to 64bit even in the 32bit targets (like mipsel24).

说的是9月份之后的SDK中，时间相关的API变成64位了。

所以你要么有最新的固件刷下机，要么就用[老版SDK（九月之前，这里提供个八月的）](https://downloads.openwrt.org/releases/19.07.8/targets/ramips/mt7621/openwrt-sdk-19.07.8-ramips-mt7621_gcc-7.5.0_musl.Linux-x86_64.tar.xz)编译。

**Comment by Shennoter** [comment]
对的，是红米AC2100，谢谢大佬解答
